### ISSUE TITLE
Questions about the main_for_real.py code

### ISSUE THREAD

**Issue by MrWan001** [Li-Tong-621/DMID#7]

**Comment by MrWan001** [comment]
Thank you for your valuable work.

I noticed that in the noise matching section, preset timesteps are assigned for each dataset. Are these timesteps obtained from the find_N function? If I want to test with other datasets, should I use the following code to obtain the matching timesteps：

difussion_times= find_N(sigma=2* noises[str(index)]['noise_level'] / 255)


![image](https://github.com/user-attachments/assets/69d73353-b8df-4f1d-b7b1-a01b2796ee0c)

**Comment by MrWan001** [comment]
Another question I would like to ask is: according to Figure 3 in the paper, since the image undergoes noise transformation, the denoised image should go through an Inverse Transform. However, in the code, the image denoised by the diffusion model is directly saved as the final result. Is the Inverse Transform necessary?
![image](https://github.com/user-attachments/assets/c142bcd8-b691-48bc-8f84-00d9008ded38)

**Comment by Li-Tong-621** [comment]
> Thank you for your valuable work.
> 
> I noticed that in the noise matching section, preset timesteps are assigned for each dataset. Are these timesteps obtained from the find_N function? If I want to test with other datasets, should I use the following code to obtain the matching timesteps：
> 
> difussion_times= find_N(sigma=2* noises[str(index)]['noise_level'] / 255)
> 
> ![image](https://private-user-images.githubusercontent.com/126931904/382478957-69d73353-b8df-4f1d-b7b1-a01b2796ee0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTg2MjMsIm5iZiI6MTczMDU1ODMyMywicGF0aCI6Ii8xMjY5MzE5MDQvMzgyNDc4OTU3LTY5ZDczMzUzLWI4ZGYtNGYxZC1iN2IxLWEwMWIyNzk2ZWUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNDM4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDY2ZDRjN2NiNGIxOWMzZTEyYTkxYmVhODY1MzQ5MTU4MDIwOTZmYzVhODc4ZGE5NDMyOGRlMmNjYzM3ODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KyGLqltoRBh_QINOt-R766eFhIIQhTD2KQFIL8A1RS0)

hi~
1.you are right! The timesteps obtained from the find_N function. Because I don't want to rerun every test, I just run one time and directly set it to a fixed value in the code.

2.If you want to test with other datasets, you can first perform noise transformation and then denoise the intermediate image.

```python
python main_for_real_NT.py
python main_for_real.py
```

Note that in `python main_for_real_NT.py`, we need to set some parameters, such as the noise level parameter `sigma` related to the noise level of the images (line 430: `sigma=data_dct['sigma']`), and the parameter `eps` for determining the stopping condition (line 445: `eps=data_dct['eps']`).

Running `python main_for_real_NT.py` successfully will generate a `.pt` file, after which we can run the `main_for_real.py` file. When running `main_for_real.py`, we need to find an appropriate step like line 155: `diffusion_times = find_N(sigma=2 * noises[str(index)]['noise_level'] / 255)`.

In general, choosing appropriate parameters can yield very good results. For easier operation or comparison, feel free to make some changes, for example, use a fixed stopping condition, such as running 4500 or 5000 iterations fixed for each image.

If you need results from some commonly used datasets, we may also be able to provide them directly.

**Comment by Li-Tong-621** [comment]
> Another question I would like to ask is: according to Figure 3 in the paper, since the image undergoes noise transformation, the denoised image should go through an Inverse Transform. However, in the code, the image denoised by the diffusion model is directly saved as the final result. Is the Inverse Transform necessary? ![image](https://private-user-images.githubusercontent.com/126931904/382479174-c142bcd8-b691-48bc-8f84-00d9008ded38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTk3NTcsIm5iZiI6MTczMDU1OTQ1NywicGF0aCI6Ii8xMjY5MzE5MDQvMzgyNDc5MTc0LWMxNDJiY2Q4LWI2OTEtNDhiYy04Zjg0LTAwZDkwMDhkZWQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNDU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTU1ZTA0MzAwZjJkMzdmZmFkMzFjYTA0NTlhZDI5MWExZWQyYjdhYzI4MDYyODQwMWZiOTMwOGM1ZGQ2YTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zYF7fV-JrPJKU9YmEMLhF4TYmDEo1SiPpC19ubQA9pY)

The images in the code mainly are inversed from [-1,1] to [0,1].

The function Transform(y) serves as both a noise transformation technique and a data normalizer. 
The noise transformation can result in image range changes and the data normalizer modifies the image range to the range of [-1, 1].
As the inverse operation of Transform(y), the inverse transform is essential for recovering the image range caused by both the noise transformation and the data normalizer. Therefore, the inverse transform acts as both the reverse noise transformation and the reverse data normalizer.

In the paper, we focus on the real noise, a complex unknown distribution. The noise transformation does not change the image range. Thus the inverse transform serves as the reverse data normalizer, adjusting the range of the output from [-1,1] to [0,1]. 
It is worth noting that there are also some traditional choices for noise transformation when the noise model is a known Poisson-Gaussian noise distribution. 
For example, for raw images following a Poisson-Gaussian model, we can adopt Variance-Stabilizing Transformation (VST). 
Therefore, for the completeness and extensibility of our framework, we believe it is necessary to retain the inverse transform.
